# Generated by Django 5.2.12 on 2026-04-02 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Verified', 'Verified'), ('Resolved', 'Resolved')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rescuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescuer_handshakes', to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
