# Generated by Django 5.2.12 on 2026-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_incident_last_lat_incident_last_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='mongo_alert_id',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
    ]
