# Generated by Django 5.2.12 on 2026-04-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RakshakProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakshak_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('trust_score', models.IntegerField(default=50)),
                ('face_signature_hash', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rakshak_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
