# Generated by Django 5.2.12 on 2026-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakshakprofile',
            name='safety_keyword',
            field=models.CharField(blank=True, default='emergency', max_length=50, null=True),
        ),
    ]
