# Generated by Django 5.2.12 on 2026-04-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rakshakprofile_safety_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rakshakprofile',
            old_name='face_signature_hash',
            new_name='face_signature_url',
        ),
        migrations.AddField(
            model_name='rakshakprofile',
            name='biometric_active',
            field=models.BooleanField(default=False),
        ),
    ]
