# Generated by Django 5.2.12 on 2026-04-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_face_signature_hash_rakshakprofile_face_signature_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rakshakprofile',
            old_name='face_signature_url',
            new_name='face_signature_hash',
        ),
        migrations.RemoveField(
            model_name='rakshakprofile',
            name='biometric_active',
        ),
        migrations.RemoveField(
            model_name='rakshakprofile',
            name='safety_keyword',
        ),
    ]
