# Generated by Django 5.2.12 on 2026-04-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_face_signature_url_rakshakprofile_face_signature_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakshakprofile',
            name='safety_keyword',
            field=models.CharField(blank=True, default='emergency', max_length=50, null=True),
        ),
    ]
