# Generated by Django 5.2.12 on 2026-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rakshakprofile_safety_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakshakprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
